### PR TITLE
Init Starting merge HTML project with PHP/PDO. Waiting for next files.

### PR DESCRIPTION
**Pull request by AriusII**
Waiting for Author Reply.

### CODE REVIEW

**Comment by PivanDepolo** [comment]
Thanks for your contribution! 

I see that you did refactoring to make website more dynamic, but some functionality is missing: login, registration system, etc.

There is code for connection to database, but there is no code for other functionality related to session managment (i think that approach with URL parameters is not suitable in this case).

**Comment by AriusII** [comment]
Hello @PivanDepolo ,
You have right but like as said ( #1 ), I was waiting for the next template files.

When the "account panel template" or if you add a .CSS Style as a div login/register results, are here, I'll add all the rest of the code; the session, login on ( azeroth core? ), a working register(pdo result).
(....)
Cause; I can't imagine what you will add and it's better to do the code when you add more informations.
+ maybe this with can motive you to continue?

It's why PDO and functions are here.

Thanks for read. @AriusII

**Comment by PivanDepolo** [comment]
> Hello @PivanDepolo ,
> You have right but like as said ( #1 ), I was waiting for the next template files.
> 
> When the "account panel template" or if you add a .CSS Style as a div login/register results, are here, I'll add all the rest of the code; the session, login on ( azeroth? ), a working register.
> (....)
> Cause; I can't imagine what you will add and it's better to do the code when you add more informations.
> 
> * maybe this with can motive you to continue?
> 
> It's why PDO and functions are here.
> 
> Thanks for read. @AriusII

This is only a template repository so i keep it HTML only for now. If you need fully scripted website for AzerothCore for example, then i will publish it soon. If you want to connect this template with any wow server feel free to fork it and add all necessary php code.

**Comment by AriusII** [comment]
Re.
Right, let's do it !
Pending to your BFA-PHP-Template repositories.
And we will see !
👍

**Pull request closed without merging**
